### ISSUE TITLE
Rubygo for all of glimmer?

### ISSUE THREAD

**Issue by rubyFeedback** [timbot1789/rubygo#1]
Hello there,

Could this also be added for glimmer-web (perhaps using javascript, or the glimmer wrapper),
as well as other toolkits if glimmer supports it? (SWT, gtk etc...)

Perhaps Andy can give pointers. I guess the best would be for rubygo to be playable via the
browser too.

(If this already works, please ignore this. If this is too much effort, please feel free to ignore
it as well. My line of thought was that one code base could be used for as many different
GUIs as possible.)

**Comment by timbot1789** [comment]
I plan to work on a glimmer-web port soon. I'm interested in testing out glimmer-web + webview to make cross-platform applications, and a simpler app like this would be a good demo case. 

I don't have any intention right now of moving the app to any other glimmer toolkits. I'm not sure how cross-compatible the code is, and I don't really have the time to go through the setup steps and testing for each of them.
